site_name: Exist developers
site_url: https://developer.exist.io/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - content.tabs.link
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Home": 
    - "Welcome": index.md
  - "Guide": 
    - "Getting started": guide/index.md
    - "Reading your data": guide/read_client.md
    - "Writing new data": guide/write_client.md
    - "Sharing your integration": guide/integration.md
    - "Best practices": guide/best_practices.md
    - "Migrating from API 1": guide/migrating.md
    - "Support": guide/support.md
  - "Reference": 
    - "Important values": reference/important_values.md
    - "Object types and terminology": reference/object_types.md
    - "Authentication": 
      - "Overview": reference/authentication/index.md
      - "Token authenticaton": reference/authentication/token.md
      - "OAuth2 authentication": reference/authentication/oauth2.md
    - "Reading data":
      - "Attributes": reference/attributes.md
      - "Correlations": reference/correlations.md
      - "Insights": reference/insights.md
      - "Averages": reference/averages.md
      - "Users": reference/users.md
    - "Writing data":  
      - "Attribute ownership": reference/attribute_ownership.md
      - "Creating attributes": reference/creating_attributes.md
      - "Updating values": reference/writing_data.md
    - "Changelog": reference/changelog.md
